# Discord settings:

bot_token: 
client_id: 
status_message: 

allow_dms: true
allowed_channel_ids: []
allowed_role_ids: []
blocked_user_ids: []

max_text: 100000
max_images: 5
max_messages: 25

use_plain_responses: false

# LLM settings:

providers:
  openai:
    base_url: https://api.openai.com/v1
    api_keys:
      - your-openai-api-key-1
      - your-openai-api-key-2
      # Add more keys as needed
  x-ai:
    base_url: https://api.x.ai/v1
    api_keys:
      - your-xai-api-key-1
      - your-xai-api-key-2
      # Add more keys as needed
  mistral:
    base_url: https://api.mistral.ai/v1
    api_keys: []
  groq:
    base_url: https://api.groq.com/openai/v1
    api_keys: []
  openrouter:
    base_url: https://openrouter.ai/api/v1
    api_keys: []
  ollama:
    base_url: http://localhost:11434/v1
  lmstudio:
    base_url: http://localhost:1234/v1
  vllm:
    base_url: http://localhost:8000/v1
  oobabooga:
    base_url: http://localhost:5000/v1
  jan:
    base_url: http://localhost:1337/v1

model: openai/gpt-4o

extra_api_parameters:
  max_tokens: 4096
  temperature: 1.0

rephraser_model: openai/gpt-4o-mini

rephraser_extra_api_parameters:
  max_tokens: 4096
  temperature: 0.7

query_splitter_model: openai/gpt-4o-mini

query_splitter_extra_api_parameters:
  max_tokens: 4096
  temperature: 0.5

system_prompt: >
  You are a helpful assistant. Cite the most relevant search results as needed to answer the question, avoiding irrelevant ones. Write only the response and use markdown for formatting. Include a clickable hyperlink at the end of the corresponding sentence, using the name of the site as the link text (e.g., [Wikipedia](https://example.com) or [ResearchGate](https://example.com)).

# Serper API settings:
serper_api_keys:
  - your-serper-api-key-1
  - your-serper-api-key-2
  # Add more keys as needed

# SerpApi settings:
serpapi_api_keys:
  - your-serpapi-api-key-1
  - your-serpapi-api-key-2
  # Add more keys as needed

# YouTube API settings:
youtube_api_keys:
  - your-youtube-api-key-1
  - your-youtube-api-key-2
  # Add more keys as needed

# Reddit API settings:
reddit_credentials:
  - client_id: your-reddit-client-id-1
    client_secret: your-reddit-client-secret-1
    user_agent: your-reddit-user-agent-1
  - client_id: your-reddit-client-id-2
    client_secret: your-reddit-client-secret-2
    user_agent: your-reddit-user-agent-2
  # Add more credentials as needed

# Maximum number of URLs to fetch and process in search queries
max_urls: 5